### ISSUE TITLE
Don't un-eject redis if it's an unsynced slave

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [twitter/twemproxy#369] opened 2015-06-15 16:57 UTC
I'm experimenting with the following setup. 1 master Redis DB (not connected/related to twemproxy) replicates to N read slaves. The pool of read slaves are managed as a single twemproxy pool. The key distribution is 'random' since every slave has the full data set.

When a slave dies, twemproxy takes it out of the pool due to `auto_eject_hosts` being set. The problem I have is that when if the slave is restored, then it will start accepting connections before it's fully synced (standard Redis behaviour). Reads against this slave will give `(error) LOADING Redis is loading the dataset in memory`. Twemproxy puts it back in the pool and now 1/N commands will start to fail with this error. It would be really nice if Twemproxy were able to check for this condition (enabled by a new config option?) and not reinstate the slave until it's fully synced.

Would that behaviour be of use to anyone else? Interested in comments on the idea and if there's any appetite for it before I consider dusting off my C hat...

**Comment by manjuraj** [comment] 2015-06-15 23:12
The fix would involve the following
+ change the response parser to recognize `-ERR LOADING Redis is loading the dataset in memory` response. Let's name this response as ERR_LOADING enum. The current implementation only recognizes whether the response is error or not. The new change would require to take the parsing one step further for -ERR responses.
+ eject a host, if the response is an ERR_LOADING resposne

**Comment by manjuraj** [comment] 2015-06-16 06:57
part 1 of the above fix has been checked in: https://github.com/twitter/twemproxy/commit/5e082b8d3ae0479b8f019a5f53e1e289f66ddfe9

**Comment by tom-dalton-fanduel** [comment] 2015-06-17 09:08
I had a look at what part 2 would involve yesterday, but I'm not sure where the 'right' place for the new check would be (we can check `msg->type == RSP_REDIS_ERROR_LOADING`, maybe in `rsp_forward`?). Even if I knew the right place for the check, I'm not sure how to eject a server from the pool - I assume we call `server_failure` but it needs the server passed and I'm not sure how we get that from the `conn`. I also don't know if it would need anything 'extra' to handle anything else once the server's ejected, or if server_failure does it all for us.

**Comment by manjuraj** [comment] 2015-06-17 17:28
No worries, thanks for giving it a shot. 

I've fixed this here: https://github.com/twitter/twemproxy/commit/ef453130e321974b332dd99d585ae7285eee4b5d. Note that in this patch, I'm regarding error strings `-OOM`, `-BUSY` and `-LOADING` as transient failures

Would really appreciate if you could test it and let me know if it works as intended.

**Comment by tom-dalton-fanduel** [comment] 2015-06-18 09:07
Thanks very much - will test this in the next few [working] days and let you know how it looks.

**Comment by tom-dalton-fanduel** [comment] 2015-06-18 13:16
I've been doing some testing on this and it seems to work well :-) The only issue I have found is that when Redis returns any of the 'transient failure' codes, the error passed back to the client will always be an 'Invalid Argument' error, rather than the actual transient error. I assume it's because of https://github.com/twitter/twemproxy/commit/ef453130e321974b332dd99d585ae7285eee4b5d#diff-58e034be09d03afa76ee03064fba0055R200. If I'm reading it right, this is because the connection->error is and `errorno` value rather than a Redis error (string/whatever), but I can't see where later on the conn->err (EINVAL) is then mapped back to a redis 'Invalid Argument' error (but it must be there somewhere!).

I don't know how hard/sensible it would be for the redis_failure (and memcache_failure) functions to return an errorno (or 0) that can be sensibly mapped back to a redis client error so that the client can get the 'correct' error message:

```
MSG_RSP_REDIS_ERROR_OOM -> ENOMEM
MSG_RSP_REDIS_ERROR_BUSY -> EBUSY?
MSG_RSP_REDIS_ERROR_LOADING -> EAGAIN?
```

This isn't a huge deal, this patch would work for us as-is, but I guess others might want to preserve the error (and we might want to handle loading differently than nomemory at some point). I guess some people (again, I don't think we need it to be at the moment) might want this new functionality to be configurable if they're already handling loading errors themselves.

Overall this is really nice - thank you very much!

**Comment by manjuraj** [comment] 2015-06-18 17:01
The conversion happens here:
* https://github.com/twitter/twemproxy/blob/master/src/nc_response.c#L331-L332
* https://github.com/twitter/twemproxy/blob/master/src/nc_response.c#L83
* https://github.com/twitter/twemproxy/blob/master/src/nc_message.c#L326-L356

I agree that it would be nice to pass back the error code from the redis server as-is to the client. However, doing that would require a significant rewrite. I'll leave it as-is and we can come back to it if it is really needed

**Closed by manjuraj** 2015-06-18 17:01 UTC
