### ISSUE TITLE
"get " let twemproxy core dump

### ISSUE THREAD

**Issue by deep011** [twitter/twemproxy#357] opened 2015-05-12 03:35 UTC
hi, when i use memcache below twemproxy, and i use telnet to execute "get ", then twemproxy core dump:

/data/app/twemproxy-master/sbin/nutcracker(nc_stacktrace_fd+0x20)[0x410300]
/data/app/twemproxy-master/sbin/nutcracker(signal_handler+0xa6)[0x40ded6]
/lib64/libpthread.so.0(+0xf710)[0x7f56afb4e710]
/data/app/twemproxy-master/sbin/nutcracker(memcache_post_coalesce+0x114)[0x413094]
/data/app/twemproxy-master/sbin/nutcracker(req_done+0x15d)[0x4093ed]
/data/app/twemproxy-master/sbin/nutcracker(rsp_recv_done+0xa3)[0x40a373]
/data/app/twemproxy-master/sbin/nutcracker(msg_recv+0xf0)[0x408fe0]
/data/app/twemproxy-master/sbin/nutcracker(core_core+0xb1)[0x405ba1]
/data/app/twemproxy-master/sbin/nutcracker(event_wait+0xc6)[0x41a606]
/data/app/twemproxy-master/sbin/nutcracker(core_loop+0x19)[0x405a49]
/data/app/twemproxy-master/sbin/nutcracker(main+0x5b8)[0x410f78]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f56af545d5d]
/data/app/twemproxy-master/sbin/nutcracker[0x405889]
[.......................] signal 11 (SIGSEGV) received, core dumping

I examine the memcache_parse_req() function and add the fllow code in the "case SW_KEY" to avoid this core dump:
if(kpos->start == kpos->end)
{
	goto error;
}

**Comment by charsyam** [comment] 2015-05-20 12:42
@deep011 could you explain more?
I tested this with master version. I can't reproduce.

**Comment by deep011** [comment] 2015-05-21 01:40
@charsyam 
first, twemproxy is for memcache;
second, telnet to twemproxy then just input get and a blank, twemproxy will core dump.

**Comment by charsyam** [comment] 2015-05-21 01:58
@deep011 Thanks. I reproduce it.
I will investigate it ASAP :)

**Comment by charsyam** [comment] 2015-05-21 13:41
@deep011 Could you try this branch?
https://github.com/charsyam/twemproxy/tree/feature/bug-fix-memcache-crash

https://github.com/twitter/twemproxy/pull/363

**Comment by charsyam** [comment] 2015-05-21 13:42
@manjuraj @idning Please review this patch :)

**Comment by manjuraj** [comment] 2015-06-17 22:13
fixed by @charsyam https://github.com/twitter/twemproxy/commit/4f717266e7e77093baf0641dd58990f560cbf82f

**Closed by manjuraj** 2015-06-17 22:13 UTC
